### ISSUE TITLE
Manage apps crash (Miui security app crashing when opening manage apps)

### ISSUE THREAD

**Issue by Ankit2502** [MonwF/customiuizer#110]
Am sorry for recent so many bug reports...

But this is weird issue I started facing recently

Miui security app keep crashing when ever I open manage apps option while customiser active in lspossed but when I disable it in lspossed issue gets resolve and as i enable it again, issue comes back too, idk which setting is putting this effect as i was using these old settings only from past few months and not had any issue like this...

https://user-images.githubusercontent.com/89592455/211437282-1fb7a740-9853-4c03-ba53-89744cc1c5e2.mp4

**Comment by MonwF** [comment]
any logs in lsposed?

**Comment by MonwF** [comment]
try to turn off privacy protection in various setting

**Comment by Ankit2502** [comment]
> try to turn off privacy protection in various setting

Not seems to work...

**Comment by MonwF** [comment]
i read the logs but got no idea. may be you can turn off settings in various or remove security center from lsopsed scope

**Comment by Ankit2502** [comment]
> i read the logs but got no idea. may be you can turn off settings in various or remove security center from lsopsed scope

Well removing it from lspossed fix issue, but lose the feature of time skip..
Btw I tried downgrade customiser and still issue wasn't fixed..

When security app it ask me to send report/ feedback here it is

java.lang.ArrayIndexOutOfBoundsException: length=4; index=4
	at com.miui.appmanager.fragment.ManageFragment.a(Unknown Source:29)
	at com.miui.appmanager.fragment.ManageFragment.a(Unknown Source:2)
	at c.o.a.b$b.a(Unknown Source:46)
	at androidx.lifecycle.LiveData.b(Unknown Source:29)
	at androidx.lifecycle.LiveData.a(Unknown Source:44)
	at androidx.lifecycle.LiveData.b(Unknown Source:14)
	at androidx.lifecycle.s.b(Unknown Source:0)
	at c.o.a.b$a.b(Unknown Source:0)
	at c.o.a.b$a.a(Unknown Source:36)
	at c.o.b.c.b(Unknown Source:4)
	at com.miui.common.q.c.b(Unknown Source:13)
	at c.o.b.a.b(Unknown Source:30)
	at c.o.b.a$a.c(Unknown Source:2)
	at c.o.b.d.a(Unknown Source:10)
	at c.o.b.d$f.handleMessage(Unknown Source:28)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8266)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:577)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1074)
