### ISSUE TITLE
Bluetooth keeps stopping

### ISSUE THREAD

**Issue by wmsnp** [MonwF/customiuizer#114]
When the function Disable signature verification is enabled, the system reports Bluetooth keeps stopping
<details><summary>Error report given by MIUI</summary>
<p>

```
java.lang.RuntimeException: Unable to create service com.android.bluetooth.btservice.AdapterService: java.lang.SecurityException: You either need MANAGE_USERS, CREATE_USERS, or QUERY_USERS permission to: query user
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4669)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2256)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8136)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
Caused by: java.lang.SecurityException: You either need MANAGE_USERS, CREATE_USERS, or QUERY_USERS permission to: query user
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
	at android.os.Parcel.createException(Parcel.java:2995)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.os.Parcel.readException(Parcel.java:2920)
	at android.os.IUserManager$Stub$Proxy.getUserInfo(IUserManager.java:2211)
	at android.os.UserManager.getUserInfo(UserManager.java:2982)
	at android.os.UserManager.isGuestUser(UserManager.java:2541)
	at com.android.bluetooth.btservice.AdapterService.onCreate(AdapterService.java:621)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4656)
	... 9 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.pm.UserManagerService.checkQueryOrCreateUsersPermission(UserManagerService.java:2744)
	at com.android.server.pm.UserManagerService.getUserInfo(UserManagerService.java:1425)
	at android.os.IUserManager$Stub.onTransact(IUserManager.java:1060)
	at android.os.Binder.execTransactInternal(Binder.java:1285)
	at android.os.Binder.execTransact(Binder.java:1249)
```

</p>
</details>

System version: V14.0.23.1.3.DEV(xaga)
LSPosed version: v1.8.5(Zygisk)
CustoMIUIzer version: v23.01.06(Actually it seems to appear in the previous versions too)

**Comment by MonwF** [comment]
try and feedback
[app-release.zip](https://github.com/MonwF/customiuizer/files/10423322/app-release.zip)

**Comment by MonwF** [comment]
try to disable system integrity verify? get latest 1.21

**Comment by GabrielX3GT** [comment]
Expectation to release any fixes? To be able to use bluetooth with signature verification disabled, I have to disable bluetooth and then enable signature disablement, I restart the phone, so bluetooth works, but I can't open and pair new devices, I can pair only those that have already been stopped before setting the deactivation in corepatch or custom miuizer. Interesting that this problem only occurs to me when I install an apk that requires signature verification to be disabled, in this case, the app settings, Chinese version! When I uninstall app settings updates, bluetooth works normally again! This only happens on miui 14!

**Comment by MonwF** [comment]
> Expectation to release any fixes? To be able to use bluetooth with signature verification disabled, I have to disable bluetooth and then enable signature disablement, I restart the phone, so bluetooth works, but I can't open and pair new devices, I can pair only those that have already been stopped before setting the deactivation in corepatch or custom miuizer. Interesting that this problem only occurs to me when I install an apk that requires signature verification to be disabled, in this case, the app settings, Chinese version! When I uninstall app settings updates, bluetooth works normally again! This only happens on miui 14!

sorry. i can't reproduce this bug. so i don't know how to fix it properly. A simple way is just hook perm grant, but i don't want this bad solution

**Comment by brick2008** [comment]
Same as above，uncheck signature verification and reboot，Bluetooth work again。
System version: V14.0.2
LSPosed version: v1.8.6(Zygisk)
CustoMIUIzer version: v23.01.21

**Comment by MonwF** [comment]
[app.zip](https://github.com/MonwF/customiuizer/files/10569447/app.zip)

@brick2008

**Comment by brick2008** [comment]
Unfortunately,The test apk still not working properly.

**Comment by MonwF** [comment]
> Unfortunately,The test apk still not working properly.

your telegram account?

**Comment by brick2008** [comment]
> 

Not work,Sorry I don't know how to debug it.

**Comment by GabrielX3GT** [comment]
> experimente e [comente app-release.zip](https://github.com/MonwF/customiuizer/files/10423322/app-release.zip 
try to pair some bluetooth device with unlocked signature to reproduce the bug
