### ISSUE TITLE
question:in my lsposed logs there is that one error which is spamming my logs but i dont know what caused it

### ISSUE THREAD

**Issue by HoriKyoukosimp** [MonwF/customiuizer#151]
This is the error i got
```
[ 2023-01-31T22:41:32.323     1000:  1753:  6230 I/LSPosed-Bridge  ] [CustoMIUIzer][ForegroundMonitor]
java.lang.NoSuchFieldError: com.android.server.wm.DisplayPolicy#mFocusedApp
	at de.robv.android.xposed.XposedHelpers.lambda$findField$1(Unknown Source:6)
	at de.robv.android.xposed.XposedHelpers.j(Unknown Source:0)
	at de.robv.android.xposed.c.get(Unknown Source:24)
	at java.util.Optional.orElseThrow(Optional.java:404)
	at de.robv.android.xposed.XposedHelpers.findField(Unknown Source:25)
	at de.robv.android.xposed.XposedHelpers.getObjectField(Unknown Source:4)
	at name.mikanoshi.customiuizer.mods.GlobalActions$5.after(GlobalActions.java:17)
	at name.mikanoshi.customiuizer.utils.Helpers$MethodHook.afterHookedMethod(Helpers.java:1)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.updateSystemBarsLw(Unknown Source:18)
	at com.android.server.wm.DisplayPolicy.updateSystemUiVisibilityLw(DisplayPolicy.java:2758)
	at com.android.server.wm.DisplayPolicy.finishPostLayoutPolicyLw(DisplayPolicy.java:2067)
	at com.android.server.wm.DisplayContent.applySurfaceChangesTransaction(DisplayContent.java:4557)
	at com.android.server.wm.RootWindowContainer.applySurfaceChangesTransaction(RootWindowContainer.java:1086)
	at com.android.server.wm.RootWindowContainer.performSurfacePlacementNoTrace(RootWindowContainer.java:851)
	at com.android.server.wm.RootWindowContainer.performSurfacePlacement(RootWindowContainer.java:802)
	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop(WindowSurfacePlacer.java:199)
	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:148)
	at com.android.server.wm.WindowManagerService.relayoutWindow(WindowManagerService.java:2661)
	at com.android.server.wm.Session.relayout(Session.java:237)
	at android.view.IWindowSession$Stub.onTransact(IWindowSession.java:747)
	at com.android.server.wm.Session.onTransact(Session.java:171)
	at android.os.Binder.execTransactInternal(Binder.java:1182)
	at android.os.Binder.execTransact(Binder.java:1146)
```

I tried to read the logs and cant understand whats going on, why is this error caused, such

[LSPosed_2023-01-31T23_02_37.704421.zip](https://github.com/MonwF/customiuizer/files/10548445/LSPosed_2023-01-31T23_02_37.704421.zip) here is entire logs if you want them

Device info
Miui version: 13.0.7
Android version: 12
Device name: poco x3 gt (redmi note 10 pro 5g i believe in china)
Device codename: chopin
Lsposed version: 1.8.6 (6712)

**Comment by MonwF** [comment]
the code is for monitor foreground app.  may be incompatible with android 12

**Comment by HoriKyoukosimp** [comment]
I see, so there is nothing i have to worry? (Also is it possible to like, disable them? Because its kinda annoying seeing this getting spammed every milisecond even tho i rarely look at lsposed logs)

**Comment by MonwF** [comment]
you can turn off some options. i can't find them without computer. maybe i'll fix it tomorrow

**Comment by MonwF** [comment]
[app.zip](https://github.com/MonwF/customiuizer/files/10553117/app.zip)

**Comment by MonwF** [comment]
restart system

**Comment by HoriKyoukosimp** [comment]
> restart system

Everything seems fine now

Thanks alot!
