### ISSUE TITLE
bluetooth wont turn on when having customiuizer14 enabled

### ISSUE THREAD

**Issue by HoriKyoukosimp** [MonwF/customiuizer#173]
So hasically the title explains everything

Miui 14
Android 13 (android 12 vendor)
Poco x3 gt global

Logs: 
[LSPosed_2023-02-13T20_51_43.271643.zip](https://github.com/MonwF/customiuizer/files/10722856/LSPosed_2023-02-13T20_51_43.271643.zip)

Error info
```
java.lang.RuntimeException: Unable to create service com.android.bluetooth.btservice.AdapterService: java.lang.SecurityException: You either need MANAGE_USERS, CREATE_USERS, or QUERY_USERS permission to: query user
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4668)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2256)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8143)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
Caused by: java.lang.SecurityException: You either need MANAGE_USERS, CREATE_USERS, or QUERY_USERS permission to: query user
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
	at android.os.Parcel.createException(Parcel.java:2995)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.os.Parcel.readException(Parcel.java:2920)
	at android.os.IUserManager$Stub$Proxy.getUserInfo(IUserManager.java:2211)
	at android.os.UserManager.getUserInfo(UserManager.java:2982)
	at android.os.UserManager.isGuestUser(UserManager.java:2541)
	at com.android.bluetooth.btservice.AdapterService.onCreate(AdapterService.java:621)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4655)
	... 9 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.pm.UserManagerService.checkQueryOrCreateUsersPermission(UserManagerService.java:2744)
	at com.android.server.pm.UserManagerService.getUserInfo(UserManagerService.java:1425)
	at android.os.IUserManager$Stub.onTransact(IUserManager.java:1060)
	at android.os.Binder.execTransactInternal(Binder.java:1285)
	at android.os.Binder.execTransact(Binder.java:1249)
```

**Comment by HoriKyoukosimp** [comment]
#114 Duplicate
