### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by re7gog** [MonwF/customiuizer#265]
Something crashes, but everything works fine

`Crash unexpectedly: java.lang.RuntimeException: Unable to get provider com.android.systemui.statusbar.notification.NotificationProvider: java.lang.IllegalArgumentException: 'FalsingManager' is already registered
	at android.app.ActivityThread.installProvider(Unknown Source:446)
	at android.app.ActivityThread.installContentProviders(Unknown Source:28)
	at android.app.ActivityThread.handleBindApplication(Unknown Source:949)
	at android.app.ActivityThread.access$1600(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(Unknown Source:774)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loopOnce(Unknown Source:176)
	at android.os.Looper.loop(Unknown Source:76)
	at android.app.ActivityThread.main(Unknown Source:155)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:309)
Caused by: java.lang.IllegalArgumentException: 'FalsingManager' is already registered
	at com.android.systemui.dump.DumpManager.registerDumpable(Unknown Source:53)
	at com.android.systemui.classifier.FalsingManagerProxy.<init>(Unknown Source:41)
	at com.android.systemui.classifier.FalsingManagerProxy_Factory.newInstance(Unknown Source:8)
	at com.android.systemui.classifier.FalsingManagerProxy_Factory.get(Unknown Source:34)
	at com.android.systemui.classifier.FalsingManagerProxy_Factory.get(Unknown Source:0)
	at dagger.internal.DoubleCheck.get(Unknown Source:13)
	at dagger.internal.DelegateFactory.get(Unknown Source:4)
	at com.android.systemui.statusbar.policy.UserSwitcherController_Factory.get(Unknown Source:94)
	at com.android.systemui.statusbar.policy.UserSwitcherController_Factory.get(Unknown Source:0)
	at dagger.internal.DoubleCheck.get(Unknown Source:13)
	at dagger.internal.DelegateFactory.get(Unknown Source:4)
	at com.miui.systemui.statusbar.phone.AppLockHelper_Factory.get(Unknown Source:38)
	at com.miui.systemui.statusbar.phone.AppLockHelper_Factory.get(Unknown Source:0)
	at dagger.internal.DoubleCheck.get(Unknown Source:13)
	at com.miui.systemui.SettingsManager_Factory.get(Unknown Source:18)
	at com.miui.systemui.SettingsManager_Factory.get(Unknown Source:0)
	at dagger.internal.DoubleCheck.get(Unknown Source:13)
	at com.android.systemui.Dependency$$ExternalSyntheticLambda0.createDependency(Unknown Source:2)
	at com.android.systemui.Dependency.createDependency(Unknown Source:25)
	at com.android.systemui.Dependency.getDependencyInner(Unknown Source:9)
	at com.android.systemui.Dependency.getDependency(Unknown Source:0)
	at com.android.systemui.Dependency.get(Unknown Source:2)
	at com.android.systemui.MiuiVendorServices.initForDependency(Unknown Source:2)
	at com.android.systemui.statusbar.notification.NotificationProvider.onCreate(Unknown Source:0)
	at android.content.ContentProvider.attachInfo(Unknown Source:102)
	at android.content.ContentProvider.attachInfo(Unknown Source:1)
	at android.app.ActivityThread.installProvider(Unknown Source:264)
	... 11 more`

**Comment by MonwF** [comment]
this is normal

**Comment by re7gog** [comment]
Ok
