### ISSUE TITLE
23.04.11 SystemUI Crash

### ISSUE THREAD

**Issue by liyafe1997** [MonwF/customiuizer#270]
之前版本没问题，升级到23.04.11后，当通知中含有“时钟”App的通知时，SystemUI会崩。最简单的重现方法：设个倒计时，这样时钟App就会出现在通知中，然后锁屏再亮屏，SystemUI就崩了。
MIUI14.0.3， Android12，Redmi K30Pro

相关log:
```
[ 2023-04-24T01:37:18.485     1000: 27552: 27552 I/LSPosed-Bridge  ]   Loading class name.mikanoshi.customiuizer.MainModule
[ 2023-04-24T01:37:39.574     1000: 27552: 27552 I/LSPosed-Bridge  ] Crash unexpectedly: java.lang.IllegalStateException: com.miui.maml.ResourceManager$1.sizeOf() is reporting inconsistent results!
	at android.util.LruCache.trimToSize(LruCache.java:203)
	at android.util.LruCache.evictAll(LruCache.java:311)
	at com.miui.maml.ResourceManager.finish(ResourceManager.java:426)
	at com.miui.maml.ScreenElementRoot.finish(ScreenElementRoot.java:1316)
	at com.android.keyguard.AwesomeLockScreenImp.AwesomeLockScreenView.finishRoot(AwesomeLockScreenView.java:154)
	at com.android.keyguard.AwesomeLockScreen.cleanUpView(AwesomeLockScreen.java:615)
	at com.android.keyguard.RootHolder.cleanUp(RootHolder.java:107)
	at com.android.keyguard.AwesomeLockScreen.cleanUp(AwesomeLockScreen.java:477)
	at com.android.keyguard.AwesomeLockScreen.onDetachedFromWindow(AwesomeLockScreen.java:395)
	at android.view.View.dispatchDetachedFromWindow(View.java:21166)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3967)
	at android.view.ViewGroup.removeAllViewsInLayout(ViewGroup.java:5803)
	at android.view.ViewGroup.removeAllViews(ViewGroup.java:5749)
	at com.android.systemui.statusbar.phone.MiuiNotificationPanelViewController.removeAwesomeLockScreen(MiuiNotificationPanelViewController.kt:1380)
	at com.android.systemui.statusbar.phone.MiuiNotificationPanelViewController$mKeyguardUpdateMonitorCallback$1.onKeyguardShowingChanged(MiuiNotificationPanelViewController.kt:413)
	at com.android.keyguard.injector.KeyguardUpdateMonitorInjector$handleKeyguardShowingChanged$1.invoke(KeyguardUpdateMonitorInjector.kt:72)
	at com.android.keyguard.injector.KeyguardUpdateMonitorInjector$handleKeyguardShowingChanged$1.invoke(KeyguardUpdateMonitorInjector.kt:71)
	at com.android.keyguard.injector.KeyguardUpdateMonitorInjector.forEachCallback(KeyguardUpdateMonitorInjector.kt:48)
	at com.android.keyguard.injector.KeyguardUpdateMonitorInjector.handleKeyguardShowingChanged(KeyguardUpdateMonitorInjector.kt:71)
	at com.android.keyguard.injector.KeyguardUpdateMonitorInjector.setKeyguardShowingAndOccluded(KeyguardUpdateMonitorInjector.kt:118)
	at com.android.keyguard.KeyguardUpdateMonitor.setKeyguardShowingAndOccluded(KeyguardUpdateMonitor.java:3695)
	at com.android.systemui.keyguard.KeyguardViewMediator.setShowingLocked(KeyguardViewMediator.java:3103)
	at com.android.systemui.keyguard.KeyguardViewMediator.setShowingLocked(KeyguardViewMediator.java:3089)
	at com.android.systemui.keyguard.KeyguardViewMediator.onKeyguardExitFinished(KeyguardViewMediator.java:2586)
	at com.android.systemui.keyguard.KeyguardViewMediator.handleStartKeyguardExitAnimation(KeyguardViewMediator.java:2560)
	at com.android.systemui.keyguard.KeyguardViewMediator.access$5200(KeyguardViewMediator.java:194)
	at com.android.systemui.keyguard.KeyguardViewMediator$6.handleMessage(KeyguardViewMediator.java:2027)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8293)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

[ 2023-04-24T01:40:24.226     1000: 29415: 29415 I/LSPosed-Bridge  ] Loading module name.monwf.customiuizer from /data/app/~~3GVMUJrVWY8-xMzojXuNOg==/name.monwf.customiuizer-MKvMwzN6aahTNMzGxK_NbA==/base.apk
[ 2023-04-24T01:40:24.237     1000: 29415: 29415 I/LSPosed-Bridge  ]   Loading class name.mikanoshi.customiuizer.MainModule
[ 2023-04-24T01:40:36.769     1000: 29134: 29134 I/LSPosed-Bridge  ] Crash unexpectedly: java.lang.IllegalArgumentException: class miui.systemui.controlcenter.MiuiControlCenter does not depend on interface com.android.systemui.plugins.miui.controlcenter.ControlCenterController
	at com.android.systemui.plugins.PluginDependencyProvider.get(PluginDependencyProvider.java:55)
	at com.android.systemui.plugins.PluginDependency.get(PluginDependency.java:25)
	at miui.systemui.controlcenter.dagger.ControlCenterPluginInstance.onPluginConnected(Unknown Source:7)
	at miui.systemui.controlcenter.MiuiControlCenter.onCreate(Unknown Source:13)
	at com.android.systemui.shared.plugins.PluginInstanceManager$MainHandler.handleMessage(PluginInstanceManager.java:238)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8293)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)


```

**Comment by MonwF** [comment]
崩掉直接进不去系统吗？日用a13似乎没这问题

**Comment by liyafe1997** [comment]
> 崩掉直接进不去系统吗？日用a13似乎没这问题

不是一直永久崩，只有存在时钟App的通知时才会崩，最简单的重现方法是设个倒计时。

在倒计时结束之前，确实进不去系统，锁屏可以出来，一解锁秒崩。

其它时钟App的通知也会触发这个问题，比如那个就寝通知（设置了睡觉时间，到时间就会弹出），需要在锁屏界面把这条通知推掉，解锁后才不会崩。

不知你那边是否能重现，我的是Android 12，再附上个米客的配置文件

**Comment by liyafe1997** [comment]
[customiuizer_backup_0424031344.zip](https://github.com/MonwF/customiuizer/files/11305538/customiuizer_backup_0424031344.zip)

**Comment by MonwF** [comment]
我试了下，导入后倒计时没这个问题

**Comment by liyafe1997** [comment]
澄清了，我又测试了下，确实与米客无关，与MIUI某个主题有关，碰巧我换了主题以后升级了米客
