### ISSUE TITLE
系统界面崩溃

### ISSUE THREAD

**Issue by 821938089** [MonwF/customiuizer#472]
开启了显示电池信息功能
```
java.lang.NumberFormatException: s == null
 at java.lang.Integer.parseInt(Integer.java:759)
 at java.lang.Integer.parseInt(Integer.java:915)
 at yx.handleMessage(Unknown Source:215)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:224)
 at android.os.Looper.loop(Looper.java:318)
 at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by MonwF** [comment]
请提供设置 截图 系统版本，米客版本

**Comment by 821938089** [comment]
![pic](https://github.com/MonwF/customiuizer/assets/8674809/952f3fb2-7b41-4b69-8a2a-e7759a326669)

系统版本 HyperOS 1.0.6.0 Android 14
米客版本 24.04.13

**Comment by MonwF** [comment]
没有复现，而且你这状态栏不是显示了？

**Comment by 821938089** [comment]
它是用的好好的突然崩的，目前没有再出现

**Comment by 821938089** [comment]
又崩了，能不能修复一下发个版

**Comment by MonwF** [comment]
啥机器？可以兼容下，不抛异常

**Comment by 821938089** [comment]
红米K60

**Comment by MonwF** [comment]
[app.zip](https://github.com/MonwF/customiuizer/files/15282659/app.zip)

兼容了下，再观察下

**Comment by 821938089** [comment]
好的，我试试
