### ISSUE TITLE
在任何系统对话框(例如ANRs/LowSDKWarning/OldVerApp)弹出时操作该对话将导致卡死并彻底进入黑屏随后热重启

### ISSUE THREAD

**Issue by CATBirdlong** [MonwF/customiuizer#516]
_该bug**复现概率为100%**_
在多次检查模块后**确定是pengeek导致**了该情况发生
该bug无法提供任何复现时录屏
在检查log后发现开机时pengeek频繁'访问一个空对象'(java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference) 请求高达二十余次
我无法拿出大量时间与精力来查找该空对象在何处 具体的错误代码无法分析出有效信息  unknown source占据大部分代码内容
```
[ 2024-08-20T00:29:42.408     1000:  4750:  4750 E/LSPosed-Bridge  ] [Pengeek] java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
	at ke.before(Unknown Source:204)
	at name.monwf.customiuizer.mods.utils.HookerClassHelper$MethodHook.beforeHook(Unknown Source:0)
	at C7.c(Unknown Source:32)
	at java.lang.reflect.Method.invoke(Native Method)
	at J.callback(Unknown Source:136)
	at LSPHooker_.applyDarknessInternal(Unknown Source:8)
	at com.android.systemui.statusbar.StatusBarMobileView.applyMobileState(go/retraceme f33fee6970bf589d841bad9dd8bc8a5a6bb4f53554e0c4be5567234f8affa157:892)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at J.callback(Unknown Source:193)
	at LSPHooker_.applyMobileState(Unknown Source:11)
	at com.android.systemui.statusbar.phone.StatusBarIconController$IconManager.addMobileIcon(go/retraceme f33fee6970bf589d841bad9dd8bc8a5a6bb4f53554e0c4be5567234f8affa157:14)
	at com.android.systemui.statusbar.phone.StatusBarIconController$IconManager.addHolder(go/retraceme f33fee6970bf589d841bad9dd8bc8a5a6bb4f53554e0c4be5567234f8affa157:99)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at J.callback(Unknown Source:193)
	at LSPHooker_.addHolder(Unknown Source:28)
	at com.android.systemui.statusbar.phone.MiuiLightDarkIconManager.onIconAdded(go/retraceme f33fee6970bf589d841bad9dd8bc8a5a6bb4f53554e0c4be5567234f8affa157:1)
	at com.android.systemui.statusbar.phone.StatusBarIconControllerImpl$$ExternalSyntheticLambda1.accept(go/retraceme f33fee6970bf589d841bad9dd8bc8a5a6bb4f53554e0c4be5567234f8affa157:25)
	at java.util.HashMap.forEach(HashMap.java:1423)
	at com.android.systemui.statusbar.phone.StatusBarIconControllerImpl.setIcon(go/retraceme f33fee6970bf589d841bad9dd8bc8a5a6bb4f53554e0c4be5567234f8affa157:27)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at J.callback(Unknown Source:193)
	at LSPHooker_.setIcon(Unknown Source:14)
	at com.android.systemui.statusbar.phone.StatusBarIconControllerImpl.setMobileIcons(go/retraceme f33fee6970bf589d841bad9dd8bc8a5a6bb4f53554e0c4be5567234f8affa157:55)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at J.callback(Unknown Source:193)
	at LSPHooker_.setMobileIcons(Unknown Source:14)
	at com.android.systemui.statusbar.phone.MiuiStatusBarSignalPolicy.setMobileDataIndicators(go/retraceme f33fee6970bf589d841bad9dd8bc8a5a6bb4f53554e0c4be5567234f8affa157:172)
	at com.android.systemui.statusbar.connectivity.CallbackHandler$$ExternalSyntheticLambda0.run(go/retraceme f33fee6970bf589d841bad9dd8bc8a5a6bb4f53554e0c4be5567234f8affa157:31)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8767)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```
因为特殊性 我无法提供完整日志 若您希望对此bug进行查找修复恳请联系...
另外还有这段
```
[ 2024-08-20T00:29:24.197     1000:  1927:  1927 I/LSPosed-Bridge  ] [Pengeek] Failed to hook doVibratorOn method in com.android.server.VibratorService
```
您有什么部分/功能会涉及到server vibrator service?您所写的功能为何会去hook这个部分,您所指的dovibratoron是什么

**Comment by MonwF** [comment]
1. 双排信号的hook，可能是单卡开启了双排信号
2. 闷响振动的hook
我认为和米客没关系

**Comment by CATBirdlong** [comment]
> 1. 双排信号的hook，可能是单卡开启了双排信号
> 2. 闷响振动的hook
> 我认为和米客没关系

首先 感谢您的回复

但很遗憾的是  因为时间久远 变化过大 当时的设备和环境**已无法被我复现** 或说概率极低 即使能够找到日志文件我也不认为该事件可被找出缘由

所以 总而言之  再次感谢您的回复和解读分析 最终该问题的答案或许已经石沉大海

~~_问题未被他人发现前 我也无法证明这是一个普遍型bug_~~
