### ISSUE TITLE
k60更新到1.0.13模块失效，自定义状态栏时钟格式功能开启模块就会失效

### ISSUE THREAD

**Issue by sufa3317** [MonwF/customiuizer#527]
[LSPosed_2024-09-14T23_45_20.757926.zip](https://github.com/user-attachments/files/17002984/LSPosed_2024-09-14T23_45_20.757926.zip)

**Comment by MonwF** [comment]
有空提取下系统界面apk 我看看

**Comment by sufa3317** [comment]
> Copy link

[Uploading 系统界面_20230316.0.zip…]()

**Comment by sufa3317** [comment]
> 有空提取下系统界面apk 我看看

[系统界面_20230316.0.zip](https://github.com/user-attachments/files/17036191/_20230316.0.zip)

**Comment by MonwF** [comment]
去另外 https://github.com/MonwF/customiuizer/issues/526 里面下载试试

**Comment by sufa3317** [comment]
> 去另外 #526 里面下载试试

526里面的时间格式显秒可以用了，开显示时段或者自定义格式加了aa就会失效

**Comment by sufa3317** [comment]
> > 去另外 #526 里面下载试试
> 
> 526里面的时间格式显秒可以用了，开显示时段或者自定义格式加了aa就会失效

找到问题了，设置里面时间要改12小时制，才能用显示时段功能

**Comment by MonwF** [comment]
自定义格式 日期之类的生效，aa必须得12小时？这咋也改了 等会我看下

**Comment by sufa3317** [comment]
> 自定义格式 日期之类的生效，aa必须得12小时？这咋也改了 等会我看下

刚刚重启了状态栏又开始失效了
![Screenshot_2024-09-19-12-30-22-832_name monwf customiuizer-edit](https://github.com/user-attachments/assets/fcfdf7ca-d097-4188-a0f8-150a527bca1c)
图1这个是失效的
![Screenshot_2024-09-19-12-31-58-022_name monwf customiuizer-edit](https://github.com/user-attachments/assets/bdbed47e-b61b-4e8a-8f50-18c10c03192e)
图2打开显秒能生效，开那个时段就会自动重启状态栏然后失效
图1里面那个格式删除aa就生效，前面应该是卡出来的设置里面那个显示12小时制
附上刚刚的日志
[日志.zip](https://github.com/user-attachments/files/17053561/default.zip)

**Comment by MonwF** [comment]
你这个日志里啥也没有，是不是用的去日志版

**Comment by sufa3317** [comment]
> 你这个日志里啥也没有，是不是用的去日志版

github上下的mod版lsp应该不是去日志版，可能一些模块禁用了

![Screenshot_2024-09-19-13-43-15-595_com fankes apperrorstracking](https://github.com/user-attachments/assets/64539a8d-fdc2-44d7-bcd3-965c983d4d35)

**Comment by sufa3317** [comment]
Generated by AppErrorsTracking 1.3(6)
Project URL: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: Redmi
[Device Model]: 23013RK75C
[Display]: UKQ1.230804.001 release-keys
[Android Version]: 14
[Android API Level]: 34
[System Locale]: zh_CN
[Process ID]: 30836
[User ID]: 0
[CPU ABI]: arm64-v8a
[Package Name]: com.android.systemui
[Version Name]: 20230316.0
[Version Code]: 202303160
[Target SDK]: 34
[Min SDK]: 34
[Error Type]: JVM
[Crash Time]: 2024-09-19T12:30:54.183
[Stack Trace]:
java.lang.NullPointerException
	at com.android.systemui.statusbar.policy.FakeStatusBarClockController.initState(go/retraceme 30ec74aeb1526fac9689c3bd65dd3acc901ba66f577b1461860a03d45c24496f:68)
	at com.android.systemui.statusbar.policy.FakeStatusBarClockController$onLayoutChangeListener$1.onLayoutChange(go/retraceme 30ec74aeb1526fac9689c3bd65dd3acc901ba66f577b1461860a03d45c24496f:25)
	at android.view.View.layout(Unknown Source:245)
	at android.widget.LinearLayout.setChildFrame(Unknown Source:4)
	at android.widget.LinearLayout.layoutHorizontal(Unknown Source:304)
	at android.widget.LinearLayout.onLayout(Unknown Source:9)
	at android.view.View.layout(Unknown Source:147)
	at android.view.ViewGroup.layout(Unknown Source:21)
	at android.widget.LinearLayout.setChildFrame(Unknown Source:4)
	at android.widget.LinearLayout.layoutHorizontal(Unknown Source:304)
	at android.widget.LinearLayout.onLayout(Unknown Source:9)
	at android.view.View.layout(Unknown Source:147)
	at android.view.ViewGroup.layout(Unknown Source:21)
	at android.widget.FrameLayout.layoutChildren(Unknown Source:160)
	at android.widget.FrameLayout.onLayout(Unknown Source:6)
	at android.view.View.layout(Unknown Source:147)
	at android.view.ViewGroup.layout(Unknown Source:21)
	at android.widget.FrameLayout.layoutChildren(Unknown Source:160)
	at android.widget.FrameLayout.onLayout(Unknown Source:6)
	at android.view.View.layout(Unknown Source:147)
	at android.view.ViewGroup.layout(Unknown Source:21)
	at android.widget.FrameLayout.layoutChildren(Unknown Source:160)
	at android.widget.FrameLayout.onLayout(Unknown Source:6)
	at android.view.View.layout(Unknown Source:147)
	at android.view.ViewGroup.layout(Unknown Source:21)
	at android.view.ViewRootImpl.performLayout(Unknown Source:33)
	at android.view.ViewRootImpl.performTraversals(Unknown Source:2686)
	at android.view.ViewRootImpl.doTraversal(Unknown Source:36)
	at android.view.ViewRootImpl$TraversalRunnable.run(Unknown Source:13)
	at android.view.Choreographer$CallbackRecord.run(Unknown Source:20)
	at android.view.Choreographer$CallbackRecord.run(Unknown Source:24)
	at android.view.Choreographer.doCallbacks(Unknown Source:134)
	at android.view.Choreographer.doFrame(Unknown Source:669)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Unknown Source:36)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loopOnce(Unknown Source:198)
	at android.os.Looper.loop(Unknown Source:83)
	at android.app.ActivityThread.main(Unknown Source:123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:374)

**Comment by sufa3317** [comment]
> 自定义格式 日期之类的生效，aa必须得12小时？这咋也改了 等会我看下

![Screenshot_2024-09-19-13-55-24-064_name monwf customiuizer-edit](https://github.com/user-attachments/assets/52d74661-9edf-4459-a5f7-59c37365dd7b)
先不开时段这个重启状态栏模块生效，再开显示时段有概率能卡出来显示成功，有时候就会突然重启状态栏，然后模块失效，卡出来了显示时段，只要重启状态栏模块必失效

**Comment by MonwF** [comment]
是的，这里要想不重启，只要把时间放最前面。其他日期、时段之类的放后面就行，比如 HH:mm:ss aa 之类的

**Comment by sufa3317** [comment]
> 是的，这里要想不重启，只要把时间放最前面。其他日期、时段之类的放后面就行，比如 HH:mm:ss aa 之类的

确实，放时间后面能用了，只不过不大美观

**Comment by liwenjie119** [comment]
> 是的，这里要想不重启，只要把时间放最前面。其他日期、时段之类的放后面就行，比如 HH:mm:ss aa 之类的
试了，只要时间前面有任何代码，都会崩溃不生效，看看log有没有相关的内容
[LSPosed_2024-09-19T14_11_06.532402.zip](https://github.com/user-attachments/files/17054463/LSPosed_2024-09-19T14_11_06.532402.zip)

**Comment by MonwF** [comment]
日志前几天看过了，hyperos下时钟动画导致的

**Comment by sufa3317** [comment]
> 日志前几天看过了，hyperos下时钟动画导致的

有解吗

**Comment by liwenjie119** [comment]
> 日志前几天看过了，hyperos下时钟动画导致的
下拉通知栏的时候，时钟会先变成不带格式的，然后放大。
我发现把通知中心的时钟设置开开，格式设置成hh:mm:ss后，由于和状态栏都带秒，动画能正常完成，因此再在状态栏的时间格式前面加前缀也不会导致界面重启和失效了

**Comment by sufa3317** [comment]
> > 日志前几天看过了，hyperos下时钟动画导致的
> 
> 下拉通知栏的时候，时钟会先变成不带格式的，然后放大。 我发现把通知中心的时钟设置开开，格式设置成hh:mm:ss后，由于和状态栏都带秒，动画能正常完成，因此再在状态栏的时间格式前面加前缀也不会导致界面重启和失效了

我这通知中心的时钟格式，跟状态栏一样的一样会失效

**Comment by liwenjie119** [comment]
> 和通知中心时钟格式无关，只要状态栏时钟格式的前三个字符里面没有':'，就会失效. hyperos的动画实现是2个时钟进行过渡转换，有个逻辑是如果格式长短不一致，是右对齐还是左对齐进行动画过渡。这个过程中，代码没有初始化，导致报错。比较好的方案是_小米_自己修

那就不知道了，我现在是处于可用的状态，可能比较玄学
![Screenshot_2024-09-19-20-14-00-296_com chrome canary-edit](https://github.com/user-attachments/assets/758d6a63-5371-4fa7-9bf6-15c456e7c6b1)
![Screenshot_2024-09-19-20-13-55-576_com chrome canary](https://github.com/user-attachments/assets/862fa8da-92a3-422c-853c-9e313702b374)

**Comment by MonwF** [comment]
[app.zip](https://github.com/user-attachments/files/17114007/app.zip)
再试试 @liwenjie119

**Comment by liwenjie119** [comment]
> [app.zip](https://github.com/user-attachments/files/17114007/app.zip) 再试试 @liwenjie119

目前已经可用

**Comment by MonwF** [comment]
> > [app.zip](https://github.com/user-attachments/files/17114007/app.zip) 再试试 @liwenjie119
> 
> 目前已经可用

ok

**Comment by sufa3317** [comment]
> [app.zip](https://github.com/user-attachments/files/17114007/app.zip) 再试试 @liwenjie119

![Screenshot_2024-09-25-14-25-37-777_com fankes apperrorstracking](https://github.com/user-attachments/assets/12e4602b-062a-4d56-ac70-c9565ccf1164)
可以用了，下拉通知栏有概率会重启状态栏。

**Comment by MonwF** [comment]
这个也说过很多次了，要么重启系统界面后，轻轻在右侧下拉一次控制中心，要么禁用下拉动画
