### ISSUE TITLE
BUG statusbar MIUI 14

### ISSUE THREAD

**Issue by sq-dev** [MonwF/customiuizer#87]

**Comment by sq-dev** [comment]
![Screenshot_2022-12-26-10-41-58-180_name.monwf.customiuizer.jpg](https://user-images.githubusercontent.com/79777081/209507943-9be2ce8d-9e09-4f81-86a3-887d1f32e648.jpg)

Not working:
- Show SIM signal in dual row
- Show LTE for 4g

**Comment by MonwF** [comment]
get customiuizer13-1224-test.apk from https://tpsx.lanzouv.com/b021ly4gj
password: miui

this build fixed show lte for 4g and scramble pin

**Comment by sq-dev** [comment]
> get customiuizer13-1224-test.apk from https://tpsx.lanzouv.com/b021ly4gj
> password: miui
> 
> this build fixed show lte for 4g and scramble pin

4g changed to LTE
dual row sim not working

**Comment by MonwF** [comment]
i never said dual row sim was fixed. please keep waiting until i get a phone with miui 14

**Comment by sq-dev** [comment]
> i never said dual row sim was fixed. please keep waiting until i get a phone with miui 14

😁, ok thanks a lot

**Comment by MonwF** [comment]
> > i never said dual row sim was fixed. please keep waiting until i get a phone with miui 14
> 
> 😁, ok thanks a lot

any error log in lsp? Dual row signal in some devices with miui 14 works great

**Comment by sq-dev** [comment]
```
----part 2 start----
[ 2022-12-26T21:26:48.664    10290:  9932:  9932 I/LSPosed-Bridge  ] Loading module name.monwf.customiuizer from /data/app/~~aHJIMKL-Sp3ED2GfhhvvrA==/name.monwf.customiuizer-zTleKhM5Q56LsZJdBIAcaQ==/base.apk
[ 2022-12-26T21:26:48.676    10290:  9932:  9932 I/LSPosed-Bridge  ]   Loading class name.mikanoshi.customiuizer.MainModule
[ 2022-12-26T21:27:11.076     1000: 10142: 10142 I/LSPosed-Bridge  ] Loading module name.monwf.customiuizer from /data/app/~~aHJIMKL-Sp3ED2GfhhvvrA==/name.monwf.customiuizer-zTleKhM5Q56LsZJdBIAcaQ==/base.apk
[ 2022-12-26T21:27:11.084     1000: 10142: 10142 I/LSPosed-Bridge  ]   Loading class name.mikanoshi.customiuizer.MainModule
[ 2022-12-26T21:27:11.191     1000: 10142: 10142 I/LSPosed-Bridge  ] [CustoMIUIzer][NoMoreIconHook] Failed to hook setIconsVisibility method in com.android.systemui.statusbar.phone.NotificationIconAreaController
[ 2022-12-26T21:27:11.207     1000: 10142: 10142 I/LSPosed-Bridge  ] [CustoMIUIzer][HideLockScreenClockHook] Failed to hook setKeyguardStatusViewVisibility method in com.android.systemui.statusbar.phone.NotificationPanelView
[ 2022-12-26T21:27:11.214     1000: 10142: 10142 E/LSPosed-Bridge  ] java.lang.NoSuchMethodError: com.android.keyguard.utils.MiuiKeyguardUtils#supportExpandableStatusbarUnderKeyguard()#exact
	at de.robv.android.xposed.XposedHelpers.lambda$findMethodExact$3(Unknown Source:6)
	at de.robv.android.xposed.XposedHelpers.h(Unknown Source:0)
	at de.robv.android.xposed.d.get(Unknown Source:15)
	at java.util.Optional.orElseThrow(Optional.java:404)
	at de.robv.android.xposed.XposedHelpers.findMethodExact(Unknown Source:25)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(Unknown Source:27)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(Unknown Source:4)
	at name.mikanoshi.customiuizer.mods.System.SecureControlCenterHook(System.java:19)
	at name.mikanoshi.customiuizer.MainModule.handleLoadPackage(MainModule.java:228)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:26)
	at K.afterHookedMethod(Unknown Source:202)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.getClassLoader(Unknown Source:8)
	at android.app.LoadedApk.getResources(Unknown Source:50)
	at android.app.ContextImpl.createAppContext(Unknown Source:22)
	at android.app.ContextImpl.createAppContext(Unknown Source:1)
	at android.app.ActivityThread.handleBindApplication(Unknown Source:708)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(Unknown Source:878)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loopOnce(Unknown Source:182)
	at android.os.Looper.loop(Unknown Source:82)
	at android.app.ActivityThread.main(Unknown Source:123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:312)

```

**Comment by sq-dev** [comment]
> > > i never said dual row sim was fixed. please keep waiting until i get a phone with miui 14
> > 
> > 😁, ok thanks a lot
> 
> any error log in lsp? Dual row signal in some devices with miui 14 works great

it's help?

**Comment by MonwF** [comment]
> > > > i never said dual row sim was fixed. please keep waiting until i get a phone with miui 14
> > > 
> > > 
> > > 😁, ok thanks a lot
> > 
> > 
> > any error log in lsp? Dual row signal in some devices with miui 14 works great
> 
> it's help?

no. without any helpful log

**Comment by MonwF** [comment]
get latest build and try it

**Comment by sq-dev** [comment]
> get latest build and try it

![Screenshot_2022-12-29-18-05-39-001_com.miui.home.png](https://user-images.githubusercontent.com/79777081/209955420-bd6b7e48-3fb8-41a0-9a2f-36f99187b396.png)
LOL

**Comment by MonwF** [comment]
disable dual row system icons if you just want dual signal

**Comment by sq-dev** [comment]
> disable dual row system icons if you just want dual signal

Thanks a lot, its fixed
